"""migracion

Revision ID: 6e0c7337ec90
Revises: 
Create Date: 2025-03-13 15:03:22.748338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0c7337ec90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriado',
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_name', sa.String(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_renounceable', sa.Boolean(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_index(op.f('ix_feriado_holiday_id'), 'feriado', ['holiday_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feriado_holiday_id'), table_name='feriado')
    op.drop_table('feriado')
    # ### end Alembic commands ###
